#General settings
[general]
	#Determines whether to add speed bouns as a percentage.
	#If enable, the bonus will be calculated as a percentage.
	umasoul_speed_percent_enable = true
	#Determining the max speed of umamusume soul.
	#Set to 0 will not add any speed.
	# Default: 1.2
	# Range: 0.0 ~ 1.7976931348623157E308
	umasoul_max_speed = 0.5
	#Determines whether to add strength bouns as a percentage.
	#If enable, the bonus will be calculated as a percentage.
	umasoul_strength_percent_enable = true
	#Determining the max attack of umamusume soul.
	#Set to 0 will not add any attack.
	# Default: 2.0
	# Range: 0.0 ~ 1.7976931348623157E308
	umasoul_max_strength_attack = 4.0
	#Determines whether to add stamina bouns as a percentage.
	#If enable, the bonus will be calculated as a percentage.
	umasoul_stamina_percent_enable = true
	#Determining the max health of umamusume soul.
	#Set to 0 will not add any health.
	# Default: 20.0
	# Range: 0.0 ~ 1.7976931348623157E308
	umasoul_max_stamina_health = 0.25
	#Determines whether to add guts bouns as a percentage.
	#If enable, the bonus will be calculated as a percentage.
	umasoul_guts_percent_enable = true
	#Determining the max armor of umamusume soul.
	#Set to 0 will not add any health.
	# Default: 5.0
	# Range: 0.0 ~ 1.7976931348623157E308
	umasoul_max_guts_armor = 0.25
	#Determining the max armor toughness of umamusume soul.
	#Set to 0 will not add any health.
	# Default: 4.0
	# Range: 0.0 ~ 1.7976931348623157E308
	umasoul_max_guts_armor_toughness = 0.2
	#Determining the chance that damage will effect motivation.
	#Set to 0 to turn off.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	chance_motivation_effect = 0.5
	#Determining the damage that will effect motivation.
	#Set to 0 to turn off.
	# Default: 4.0
	# Range: 0.0 ~ 1.7976931348623157E308
	damage_motivation_effect = 4.0
	#Determining the sum of gacha probabilities.
	#If the sum of the three gacha probabilities does not equal the expected sum, follow the default configuration.
	# Default: 100
	# Range: > 3
	gacha_probability_sum = 100
	#Determining the R ranking probability of gacha probabilities.
	#If the sum of the three gacha probabilities does not equal the expected sum, follow the default configuration.
	# Default: 70
	# Range: > 1
	gacha_probability_r = 88
	#Determining the SR ranking probability of gacha probabilities.
	#If the sum of the three gacha probabilities does not equal the expected sum, follow the default configuration.
	# Default: 20
	# Range: > 1
	gacha_probability_sr = 10
	#Determining the SSR ranking probability of gacha probabilities.
	#If the sum of the three gacha probabilities does not equal the expected sum, follow the default configuration.
	# Default: 10
	# Range: > 1
	gacha_probability_ssr = 2
	#Determines the threshold for all base stat values.
	#If the threshold value is exceeded, the attribute effect will be reduced according to stat_limit_reduction.
	#Some attribute effects no longer increase after exceeding the threshold
	# Default: 18
	# Range: > 18
	stat_limit_value = 18
	#Determines the reduction for all base stat values.
	#If the threshold value is exceeded, the attribute effect will be reduced according to this value.
	# Default: 0.6
	# Range: 0.0 ~ 1.0
	stat_limit_reduction = 0.6
